# Generated by Django 4.2.23 on 2025-07-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_sa43oj', upload_to='images/'),
        ),
    ]
