# Generated by Django 4.2.23 on 2025-10-05 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_kids', models.IntegerField(default=1)),
                ('num_married', models.IntegerField(default=1)),
                ('tertiary_education', models.IntegerField(default=1)),
                ('cooker', models.IntegerField(default=1)),
                ('neat', models.IntegerField(default=1)),
                ('steady_income', models.IntegerField(default=1)),
                ('personality', models.IntegerField(default=1)),
                ('spirituality', models.IntegerField(default=1)),
                ('innocence', models.IntegerField(default=1)),
                ('premium_plan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
