# Generated by Django 4.2.23 on 2025-10-08 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='num_kids',
            new_name='numKids',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='num_married',
            new_name='numMarried',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='steady_income',
            new_name='steadyIncome',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='tertiary_education',
            new_name='tertiaryEducation',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='premium_plan',
        ),
        migrations.AddField(
            model_name='quote',
            name='premiumPlan',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
